
CREATE TABLE `ledger_sheets` (
  `LEDGER_SHEETS_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `LEDGER_SHEETS_NAME` varchar(45) DEFAULT NULL,
  `LEDGER_UNIQUE_SHEET_ID` varchar(45) NOT NULL,
  `SYS_START_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `SYS_ACTION_ID` varchar(45) NOT NULL,
  `SYS_ACTION_NM` varchar(45) NOT NULL,
  `SYS_ACTION_CD` varchar(45) NOT NULL,
  `LAST_UPDATE_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`LEDGER_SHEETS_ID`),
  UNIQUE KEY `LEDGER_SHEETS_ID_UNIQUE` (`LEDGER_SHEETS_ID`),
  UNIQUE KEY `LEDGER_UNIQUE_SHEET_ID_UNIQUE` (`LEDGER_UNIQUE_SHEET_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;

CREATE TABLE `ledger_expenses` (
  `EXPENSE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `EXPENSE_DESC` varchar(45) DEFAULT NULL,
  `PAID_AMOUNT` varchar(45) NOT NULL,
  `PAID_BY` varchar(45) NOT NULL,
  `PAID_FOR` varchar(45) NOT NULL,
  `SYS_START_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `SYS_ACTION_ID` varchar(45) NOT NULL,
  `SYS_ACTION_NM` varchar(45) NOT NULL,
  `SYS_ACTION_CD` varchar(45) NOT NULL,
  `LAST_UPDATED_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LEDGER_SHEETS_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`EXPENSE_ID`),
  UNIQUE KEY `EXPENSE_ID_UNIQUE` (`EXPENSE_ID`),
  KEY `FK2_SHEETS_idx` (`LEDGER_SHEETS_ID`),
  CONSTRAINT `FK2_SHEETS` FOREIGN KEY (`LEDGER_SHEETS_ID`) REFERENCES `ledger_sheets` (`LEDGER_SHEETS_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `ledger_user_groups` (
  `LEDGER_USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `LEDGER_USER_NAME` varchar(45) NOT NULL,
  `LEDGER_DISPLAY_NAME` varchar(45) NOT NULL,
  `LEDGER_BALANCED_AMT` varchar(45) DEFAULT NULL,
  `SYS_START_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `SYS_ACTION_ID` varchar(45) NOT NULL,
  `SYS_ACTION_NM` varchar(45) NOT NULL,
  `SYS_ACTION_CD` varchar(45) NOT NULL,
  `LAST_UPDATED_TS` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LEDGER_SHEETS_ID` bigint(20) NOT NULL,
  `LEDGER_USER_COMMENTS` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`LEDGER_USER_ID`),
  UNIQUE KEY `LEDGER_USER_ID_UNIQUE` (`LEDGER_USER_ID`),
  KEY `FK_SHEET_idx` (`LEDGER_SHEETS_ID`),
  CONSTRAINT `FK1_SHEET` FOREIGN KEY (`LEDGER_SHEETS_ID`) REFERENCES `ledger_sheets` (`LEDGER_SHEETS_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=18 DEFAULT CHARSET=utf8;
