CREATE TABLE `widgetledger`.`ledger_sheets` (
  `LEDGER_SHEETS_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `LEDGER_SHEETS_NAME` VARCHAR(45) NULL,
  `LEDGER_UNIQUE_SHEET_ID` VARCHAR(45) NULL,
  `SYS_START_TS` TIMESTAMP NULL,
  `SYS_ACTION_ID` VARCHAR(45) NULL,
  `SYS_ACTION_NM` VARCHAR(45) NULL,
  `SYS_ACTION_CD` VARCHAR(45) NULL,
  `LAST_UPDATE_TS` DATETIME NULL,
  PRIMARY KEY (`LEDGER_SHEETS_ID`),
  UNIQUE INDEX `LEDGER_SHEETS_ID_UNIQUE` (`LEDGER_SHEETS_ID` ASC),
  UNIQUE INDEX `LEDGER_UNIQUE_SHEET_ID_UNIQUE` (`LEDGER_UNIQUE_SHEET_ID` ASC));
  
  
  CREATE TABLE `widgetledger`.`ledger_expenses` (
  `EXPENSE_ID` INT NOT NULL AUTO_INCREMENT,
  `EXPENSE_DESC` VARCHAR(45) NULL,
  `PAID_AMOUNT` VARCHAR(45) NULL,
  `PAID_BY` VARCHAR(45) NULL,
  `PAID_FOR` VARCHAR(45) NULL,
  `SYS_START_TS` DATETIME NULL,
  `SYS_ACTION_ID` VARCHAR(45) NULL,
  `SYS_ACTION_NM` VARCHAR(45) NULL,
  `SYS_ACTION_CD` VARCHAR(45) NULL,
  `LAST_UPDATED_TS` DATETIME NULL,
  PRIMARY KEY (`EXPENSE_ID`),
  UNIQUE INDEX `EXPENSE_ID_UNIQUE` (`EXPENSE_ID` ASC),
  CONSTRAINT `LEDGER_SHEETS_ID`
    FOREIGN KEY (`EXPENSE_ID`)
    REFERENCES `widgetledger`.`ledger_sheets` (`LEDGER_SHEETS_ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);
   
   ALTER TABLE `widgetledger`.`ledger_expenses` 
ADD INDEX `RELATED_EXPENSES_idx` (`LEDGER_SHEETS_ID` ASC);
ALTER TABLE `widgetledger`.`ledger_expenses` 
ADD CONSTRAINT `RELATED_EXPENSES`
  FOREIGN KEY (`LEDGER_SHEETS_ID`)
  REFERENCES `widgetledger`.`ledger_sheets` (`LEDGER_SHEETS_ID`)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;
    
    CREATE TABLE `widgetledger`.`ledger_user_groups` (
  `LEDGER_USER_ID` INT NOT NULL AUTO_INCREMENT,
  `LEDGER_USER_NAME` VARCHAR(45) NULL,
  `LEDGER_DISPLAY_NAME` VARCHAR(45) NULL,
  `LEDGER_BALANCED_AMT` VARCHAR(45) NULL,
  `SYS_START_TS` DATETIME NULL,
  `SYS_ACTION_ID` VARCHAR(45) NULL,
  `SYS_ACTION_NM` VARCHAR(45) NULL,
  `SYS_ACTION_CD` VARCHAR(45) NULL,
  `LAST_UPDATED_TS` VARCHAR(45) NULL,
  PRIMARY KEY (`LEDGER_USER_ID`),
  UNIQUE INDEX `LEDGER_USER_ID_UNIQUE` (`LEDGER_USER_ID` ASC),
  CONSTRAINT `LEDGER_SHEETS_ID`
    FOREIGN KEY (`LEDGER_USER_ID`)
    REFERENCES `widgetledger`.`ledger_sheets` (`LEDGER_SHEETS_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
